# server
server:
  port: 8081
  servlet:
    context-path: /
    # encoding
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  mvc:
    cors:
      allowed-origins: http://192.168.0.16:3000/


  # mysql
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?serverTimezone=UTC&characterEncoding=UTF-8
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis
mybatis:
  config: mybatis/configuration.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# JWT
jwt:
  secret: 64461f01e1s23mf93ngr9c48d801ce59142452199ff112fb5404c8e7e98e3ff