# server 설정
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Spring 설정
spring:
  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: ${mail.username} # 3
    password: ${mail.password} # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
        mime:
          charset: UTF-8



  # CORS 설정
  mvc:
    cors:
      allowed-origins: http://192.168.0.16:3000/



  # MySQL 설정
  datasource:
    url: jdbc:mysql://localhost:3306/LUMEN?serverTimezone=UTC&characterEncoding=UTF-8
    username: LUMEN
    password: VIKING
    driver-class-name: com.mysql.cj.jdbc.Driver


  # MyBatis 설정
mybatis:
  configuration:
    cache-enabled: false          # 캐시 사용 여부를 비활성화
    use-generated-keys: true     # 자동 생성 키 사용 설정
    default-executor-type: REUSE  # SQL 세션 재사용 여부 설정
    jdbc-type-for-null: NULL      # JDBC에서 NULL 값 타입을 설정
    map-underscore-to-camel-case: true  # 스네이크 케이스를 카멜 케이스로 매핑

mybatis.type-aliases-package: com.lumen.www.dto  # Type Alias를 찾을 패키지 지정
mybatis.mapper-locations: classpath:mybatis/mapper/*.xml  # MyBatis XML 매퍼 파일 경로 설정


file:
  upload-dir: C:\\lumen\\upload\\


# JWT 설정
jwt:
  secret: 64461f01e1s23mf93ngrg2fd9501ce59142452199ff112fb5404c8e7e98e3ff

# 로그설정
logging:
  level:
    root: INFO
    com.lumen.www: DEBUG
  file:
    name: logs/myapp.log
