# server 설정
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m # 세션 만료 시간 30분

# Spring 설정
spring:
  # CORS 설정
  mvc:
    cors:
      allowed-origins: http://192.168.0.16:3000/

  # Redis 설정
  session:
    store-type: redis
    redis:
      host: localhost
      port: 6379

  # MySQL 설정
  datasource:
    url: jdbc:mysql://localhost:3306/LUMEN?serverTimezone=UTC&characterEncoding=UTF-8
    username: LUMEN
    password: VIKING
    driver-class-name: com.mysql.cj.jdbc.Driver

  # MyBatis 설정
mybatis:
  configuration:
    cache-enabled: false          # 캐시 사용 여부를 비활성화
    use-generated-keys: true     # 자동 생성 키 사용 설정
    default-executor-type: REUSE  # SQL 세션 재사용 여부 설정
    jdbc-type-for-null: NULL      # JDBC에서 NULL 값 타입을 설정
    map-underscore-to-camel-case: true  # 스네이크 케이스를 카멜 케이스로 매핑

mybatis.type-aliases-package: com.lumen.www.vo  # Type Alias를 찾을 패키지 지정
mybatis.mapper-locations: classpath:mybatis/mapper/*.xml  # MyBatis XML 매퍼 파일 경로 설정




# JWT 설정
jwt:
  secret: 64461f01e1s23mf93ngr9c48d801ce59142452199ff112fb5404c8e7e98e3ff
