# server 설정
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m # 세션 만료 시간 30분

# Spring 설정
spring:
  # CORS 설정
  mvc:
    cors:
      allowed-origins: http://192.168.0.16:3000/

  # Redis 설정
  session:
    store-type: redis
    redis:
      host: localhost
      port: 6379

  # MySQL 설정
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?serverTimezone=UTC&characterEncoding=UTF-8
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis 설정
mybatis:
  config: mybatis/configuration.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# JWT 설정
jwt:
  secret: 64461f01e1s23mf93ngr9c48d801ce59142452199ff112fb5404c8e7e98e3ff
