# server
server:
  port: 8081
  servlet:
    context-path: /
    # encoding
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  mvc:
    cors:
      allowed-origins: http://192.168.0.16:3000/
